spotiload: audioWriter.cpp image.cpp MP3Writer.cpp OGGWriter.cpp options.cpp RawWriter.cpp spotiload.cpp stdafx.cpp WAVWriter.cpp utf8.c
	g++ -I. -o ../../bin/spotiload.bin audioWriter.cpp image.cpp MP3Writer.cpp OGGWriter.cpp options.cpp RawWriter.cpp spotiload.cpp stdafx.cpp WAVWriter.cpp utf8.c \
        ../../lib/libptypes.so ../../lib/libmp3lame.so ../../lib/libspotify.so
